### ISSUE TITLE
Facebook Support

### ISSUE THREAD

**Issue by yankeyhotel** [juliancwirko/meteor-s-id#1]
I added Facebook support in a new branch. Would you like me to submit it to the master branch or a dev branch you create? You can check it out here. https://github.com/yankeyhotel/meteor-s-id

**Comment by juliancwirko** [comment]
Hey, thanks! 
You can create PR to master branch. I will not be able to test it till monday. But I will do this asap.

**Comment by juliancwirko** [comment]
Merged
