### ISSUE TITLE
Is it possible to not require a username?

### ISSUE THREAD

**Issue by yankeyhotel** [juliancwirko/meteor-s-id#3]
I can't seem to find it, but is there an equivalent to the following for s-id? I don't really need a username, an email will be plenty.

```
Accounts.ui.config({
  passwordSignupFields: 'EMAIL_ONLY'
});
```

thanks.

**Comment by juliancwirko** [comment]
Hi, for now there isn't such option. I will try to add it asap. It should be avaible in this package. Thanks.

**Comment by juliancwirko** [comment]
Ok, there is a new option in the config: `registerEmailFieldOnly: true` from version 3.1.0
Let me know if this is ok.

**Comment by juliancwirko** [comment]
I close it for now
