### ISSUE TITLE
Customize Registration flow

### ISSUE THREAD

**Issue by jaysig** [juliancwirko/meteor-s-id#4]
Is there a way to log the user in and redirect them to their account page at "/account" upon registration and could we potentially add more fields to the registration form?

**Comment by juliancwirko** [comment]
You should be able to use `onLogged` callback see the config example: https://github.com/juliancwirko/meteor-s-id#full-config-all-is-optional-and-here-you-can-overwrite-defaults 
it depends what kind of router you use but for FlowRouter you can do something like: 

```
onLogged: function () {
  FlowRouter.go('/accounts');
},
```

unfortunatelly there isn't simple way to add new fields to the registration form. You can always clone the package ot you can try with [aldeed:template-extension](https://github.com/aldeed/meteor-template-extension) but I haven't tested it yet.

**Comment by jaysig** [comment]
Yea so logging in directly works, but what we want is registration to act like logging in whereby upon registration they are logged in; so, they wouldn't have to re-input their information on a login page.

**Comment by juliancwirko** [comment]
oh, I get your point, you're right. I'll try to fix this. This is because [createUser](http://docs.meteor.com/#/full/accounts_createuser) method is called only on the server.

**Comment by jaysig** [comment]
Thanks a lot.

**Comment by juliancwirko** [comment]
Hey, there is new version 3.1.3 with a new configuration option `autoLoginAfterRegistration` (enabled in default). You can check it out.

**Comment by jaysig** [comment]
Works great and thanks again.
