### ISSUE TITLE
When using registerEmailFieldOnly, login input should be type="email"

### ISSUE THREAD

**Issue by dkmooers** [juliancwirko/meteor-s-id#5]
This would prevent auto-capitalization and auto-spaces added on mobile devices when typing in your email. (e.g. `Dkmooers@gmail. Com`)

Thanks!

**Comment by juliancwirko** [comment]
Yeah, I think this is a good idea. Will be done asap. Thanks!

**Comment by juliancwirko** [comment]
done in version 3.2.1

**Comment by dkmooers** [comment]
Thanks Julian, much appreciated! Love the simplicity of this package, scotty as well. Cheers!
